/**
 * Cloudflare Turnstile server-side verification
 *
 * Verifies the token generated by the client-side Turnstile widget
 * against Cloudflare's verification endpoint.
 */

const TURNSTILE_VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify'

export interface TurnstileVerifyResult {
  success: boolean
  error?: string
  challengeTs?: string
  hostname?: string
}

export async function verifyTurnstileToken(
  token: string,
  remoteIp?: string
): Promise<TurnstileVerifyResult> {
  const secretKey = process.env.TURNSTILE_SECRET_KEY

  if (!secretKey) {
    console.error('TURNSTILE_SECRET_KEY not configured')
    // In development without keys, allow through
    if (process.env.NODE_ENV === 'development') {
      return { success: true }
    }
    return { success: false, error: 'Turnstile not configured' }
  }

  // Skip verification for testing keys
  if (token === 'XXXX.DUMMY.TOKEN.XXXX') {
    return { success: true }
  }

  try {
    const formData = new URLSearchParams()
    formData.append('secret', secretKey)
    formData.append('response', token)
    if (remoteIp) {
      formData.append('remoteip', remoteIp)
    }

    const response = await fetch(TURNSTILE_VERIFY_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: formData,
    })

    const result = await response.json()

    if (!result.success) {
      console.log('Turnstile verification failed:', result['error-codes'])
      return {
        success: false,
        error: result['error-codes']?.join(', ') || 'Verification failed',
      }
    }

    return {
      success: true,
      challengeTs: result.challenge_ts,
      hostname: result.hostname,
    }
  } catch (error) {
    console.error('Turnstile verification error:', error)
    return {
      success: false,
      error: 'Verification request failed',
    }
  }
}
